### ISSUE TITLE
SLES support

### ISSUE THREAD

**Issue by deric** [deric/puppet-accounts#68]
Verify functionality and add SLES to supported systems.

**Comment by deric** [comment]
@redno2 I've created a [Docker image](https://hub.docker.com/r/deric/opensuse-puppet/) for testing purposes. On Docker hub there are official images of [opensuse 13.2](https://hub.docker.com/r/opensuse/amd64/tags/) and 42.2.

Currently most of the tests are passing:
```

  1) YAML declaration avoid cyclic dependency Command "groups jordi" stdout should match /jordi : jordi/
     Failure/Error: its(:stdout) { is_expected.to match /jordi : jordi/ }
       expected "jordi : users sudo it\n" to match /jordi : jordi/
       Diff:
       @@ -1,2 +1,2 @@
       -/jordi : jordi/
       +jordi : users sudo it
       
       
     # ./spec/acceptance/hiera_spec.rb:132:in `block (4 levels) in <top (required)>'

  2) YAML declaration avoid cyclic dependency Command "groups it" stdout should match /it : it sudo/
     Failure/Error: its(:stdout) { is_expected.to match /it : it sudo/ }
       expected "it : users sudo it\n" to match /it : it sudo/
       Diff:
       @@ -1,2 +1,2 @@
       -/it : it sudo/
       +it : users sudo it
       
       
     # ./spec/acceptance/hiera_spec.rb:139:in `block (4 levels) in <top (required)>'

  3) accounts defintion manage users Command "id -g deployer" stdout should match /1010/
     Failure/Error: its(:stdout) { is_expected.to match /1010/ }
       expected "100\n" to match /1010/
       Diff:
       @@ -1,2 +1,2 @@
       -/1010/
       +100
```
I'm gonna look into the failures later, hopefully it won't be hard to fix.
